### ISSUE TITLE
More than one property into google sheets

### ISSUE THREAD

**Issue by morganderek** [thinkinglabs/toggl-google-sheet#10]
Is it possible to pull more than one property into google sheets? At the moment the script imports "customer". I would like to import "project" and "description" as col 2 and 3?

**Comment by tdpauw** [comment]
For now, the sheet aggregates the timings per day per customer. This was the use case we needed to be able to invoice customers. 

You can surely extend the spreadsheet to aggregate per day, per customer, per project. For that, you need to modify 
- `Code.gs fetchTimesheet()` - who performs the aggregation and creates an array of `timesheet` objects - and 
- `Code.gs createTimesheet()` - who creates or updates a new sheet in your Google spreadsheet.

I see @nachogarrone did a similar extension in his fork: see nachogarrone/toggl-google-sheet@d03a8a8

**Comment by morganderek** [comment]
Thanks for pointing me in the right direction, that works

**Comment by tdpauw** [comment]
You're welcome @morganderek
