### ISSUE TITLE
Update API Url Domain to api.track.toggl.com

### ISSUE THREAD

**Issue by gilberthdez** [thinkinglabs/toggl-google-sheet#25]
toggl.com or www.toggl.com will no longer be a supported entry point for the Toggl Track API check:

https://github.com/toggl/toggl_api_docs
https://toggl.com/blog/api-documentation-change

**Comment by andrelung** [comment]
I created a pull request for this: https://github.com/thinkinglabs/toggl-google-sheet/pull/37

**Comment by tdpauw** [comment]
Oh gosh, I've missed this issue. I've only recently found out you have to actually turn on email notification 🤦 

Well, @andrelung PR fixes the issue. I've just merged it.
Thank you so much for reporting this and for fixing it 🎉
