### ISSUE TITLE
UrlFetchApp Error

### ISSUE THREAD

**Issue by morganderek** [thinkinglabs/toggl-google-sheet#36]
I have been getting an error code in my google sheets the last few days "Exception: Request failed for https://www.toggl.com returned code 410."

If I run a debug in google scripts it gets stuck at UrlFetchApp and the debugger says page: undefined under local variables?

**Comment by morganderek** [comment]
Ok I worked out what the problem is
You need to change the URL
From
var url = "https://www.toggl.com/reports/api/v2/details";
To
var url = "https://api.track.toggl.com/reports/api/v2/details"

See https://support.toggl.com/en/articles/5708431-why-did-my-integration-stop-working

**Comment by tdpauw** [comment]
In the meantime, this has been fixed by #37

Sorry for the late reply, I've missed your issue.
